export enum SCRAPER_ACTIONS {
  OPEN_BROWSER = "LAUNCH_BROWSER",
  OPEN_WINDOW = "OPEN_WINDOW",
  OPEN_PAGE = "OPEN_PAGE",
  CLOSE_BROWSER = "CLOSE_BROWSER",
  CLOSE_WINDOW = "CLOSE_WINDOW",
  CLOSE_PAGE = "CLOSE_PAGE",
  RUN_OPERATION = "RUN_OPERATION"
}
